export const SET_STATUS = 'SET_STATUS';
export const SET_UNSUBSCRIBERS = 'SET_UNSUBSCRIBERS';
export const SET_SOURCE = 'SET_SOURCE';
export const SET_LAST_SOURCE = 'SET_LAST_SOURCE';
export const NOT_YET_IMPLEMENTED = 'NOT_YET_IMPLEMENTED';
